---
title: "Data pipeline"
output: html_notebook
---
```{r}
library(tidyverse)
```
```{r}
write.csv(iris, "iris.csv")
```
## Read
```{r}
iris_raw = read_csv("iris.csv")
```
```{r}
library(readxl)
library(writexl)
write_xlsx(iris, "iris.xlsx")
read_excel("iris.xlsx")
```

```{reval=FALSE}
library(haven)
write_dta(iris,"iris.dta")
```

##Exploratory analysis
DataExplorer 
```{r}
DataExplorer::create_report(iris_raw, y= "Species")
```

## Querying rows
top n tails
```{r}
iris_raw %>%
  head(10)

iris_raw
tail(10)

iris_raw %>% 
  sample_n(10)
iris_raw %>% 
  sample_frac(0.10)

head(iris_raw, 10)
tail(iris_raw, 10)
sample_n(iris_raw, 10)
sample_frac(iris_raw, .10)
```
WHERE
```{r}
iris_raw %>% 
filter(Species=="setosa",Sepal.Length > 5.5)
```
Equal
Less/ Greater than
Not equal

TRUE 
FALSE
```{r}
TRUE & TRUE
TRUE & FALSE
# YELLOW & (BLUE OR RED)
TRUE & (FALSE)
TRUE & TRUE
```
```{r}
iris_raw %>% 
  filter_if(is.numeric, ~ .< 5)
```
```{r}
iris_raw %>% 
  filter_if(is.numeric, any_vars(. <1))
```

```{r}
ggplot2movies::"movies" 
 
```
```{r}
ggplot2movies:: "movies" %>% select(Action)

```

```{r}
ggplot2movies::"movies" %>% select_if(-(length>360))



```

```{r}
library(ggplot2movies)
movies %>% 
  filter(Action==1)
movies %>% 
filter(length<=6*60) 
movies %>%  # 6 hours in minutes
  summarise(max(lenght))

movies %>% 
  filter_at(vars(Action:Short),all_vars(. ==0))

```

```{r}
iris %>% 
  select (starts_with("Sepal"))
iris %>% 
  select_if(is.numeric) %>% 
prcomp()
  
```
```{r}
movies
movies %>% 
  rename(budget_if_known=budget)-> 
  movies_cleaned
movies %>% 
  select(budget_if_known=budget, everything())
```
# Longer pipelines
```{r}
iris %>% 
  filter(Species=="setosa") %>% 
  select(starts_with("Sepal."))
```
#Changing or adding columns
```{r}
iris %>% 
  mutate (Sepal.Length=Sepal.Length-0.1,Sepal.Area=Sepal.Length*Sepal.Width, Species_trun= str_trunc(as.character(Species),3),Diff.Sepal. Lenght = (Sepal.Length-mean (Sepal.Length))mean(Sepal.Length))
```
```{r}
movies
movies %>% 
  mutate(diff_length=length-median (length))-> movies_diff

```
## Aggregating our data
group= group_by
aggreation= summarise
```{r}
iris %>% 
  group_by(Species) %>% 
  summarise(count=n(), avg.Sepal.Length=mean(Sepal.Length))

iris %>% 
  group_by(Species) %>% 
  summarise_all(mean)
iris %>% 
  group_by(Species) %>% 
  mutate
```

```{r}
movies %>% 
  summarise(min(length)/60, max(length)/60)

#proportion by genre
movies %>% 
  group_by(Action, Comedy) %>% 
  summarise(n=n()) %>% 
  ungroup () %>% 
  mutate(per=n/sum(n))
  #summarise (sum(per))

  
  
```












